version: '3'

services:
  roach1:
    image: cockroachdb/cockroach
    command: start --insecure
    expose:
     - "8080"
     - "26257"
    ports:
     - "26257:26257"
     - "8080:8080"
    networks:
     - roachnet
    volumes:
     - ../roachdata/roach1:/cockroach/cockroach-data
  roach2:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach1
    networks:
     - roachnet
    volumes:
     - ../roachdata/roach2:/cockroach/cockroach-data
  roach3:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach1
    networks:
     - roachnet
    volumes:
     - ../roachdata/roach3:/cockroach/cockroach-data
  # db-init:
  #  image: cockroachdb/cockroach
  #  networks:
  #   - roachnet
  #  volumes:
  #    - ./setup_db.sh:/setup_db.sh
  #  entrypoint: "/bin/bash"
  #  command: /setup_db.sh
networks:
  roachnet: